### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by pvullioud** [PrestaSafe/erp#3]
https://github.com/PrestaSafe/erp/blob/e77a3b8403db74ae65f8013d36db8b88f193b810/models/invoice/fields.yaml#L37

OctoberCMS utilise que rarement les id directement dans un formulaire. Le mieux c'est de passé par les relations
https://octobercms.com/docs/backend/forms#widget-relation

```
currency:
    label: Currency
    type: relation
    select: identification
```
